# Generated by Django 5.1.2 on 2024-10-29 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='server.courses'),
        ),
        migrations.AddField(
            model_name='documents',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='server.proffesor_profile'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
